### ISSUE TITLE
Fail to create project due to missing "project_short_description"

### ISSUE THREAD

**Issue by adolfogc** [DerThorsten/cpp_cookiecutter#30]
Hi, I tried to create a project using your cookiecutter template, but it is failing with the following error:

```bash
Unable to create file 'LICENCE.txt'
Error message: 'collections.OrderedDict object' has no attribute 'project_short_description'
Context: {
    "cookiecutter": {
        "_copy_without_render": [
            "docs/source/_templates/*.html",
            "docs/source/_templates/*.css",
            "docs/source/_templates/*.rst",
            "docs/source/_static/css/*.css"
        ],
        "_template": "https://github.com/DerThorsten/cpp_cookiecutter",
       ... }
```

Is `project_short_description` a new required field by cookiecutter?

**Comment by nmusolino** [comment]
I encountered this error as well:
```
Unable to create file 'LICENCE.txt'
Error message: 'collections.OrderedDict object' has no attribute 'project_short_description'
```

**Comment by DerThorsten** [comment]
I'll have a look tomorrow and will push a fix, thanks for reporting!

**Comment by DerThorsten** [comment]
should be fixed, thanks for reporting and sry for the long time to fix this

**Comment by nmusolino** [comment]
Thank you for the fix and for maintaining this project!

**Comment by ashimgiyanani** [comment]
@DerThorsten : how did you resolve this error? I am unable to find, where this error might be originating from (although for my own cookiecutter template)
